

CREATE OR ALTER TRIGGER TRG_ATUALIZA_TOTAL_PEDIDO
AFTER INSERT OR UPDATE OR DELETE ON ITENS_PEDIDO
AS
DECLARE VARIABLE V_ID_PEDIDO INTEGER;
BEGIN
  -- Descobrir o ID do pedido 
  IF (INSERTING OR UPDATING) THEN
    V_ID_PEDIDO = NEW.ID_PEDIDO;
  ELSE IF (DELETING) THEN
    V_ID_PEDIDO = OLD.ID_PEDIDO;

  -- Atualizar o total do pedido
  UPDATE PEDIDO
  SET TOTAL_PEDIDO = (
    SELECT COALESCE(SUM(QUANTIDADE * VALOR_UNITARIO), 0)
    FROM ITENS_PEDIDO
    WHERE ID_PEDIDO = :V_ID_PEDIDO
  )
  WHERE ID_PEDIDO = :V_ID_PEDIDO;
END
